fieldLayouts:
  04553a8f-59ce-4a55-8619-257265acbfa3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 94563c1c-cb52-4d30-8dab-0e8ef74b298b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3dd27281-86ee-471e-bad1-8224c617f4e5 # Externe Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34d0e845-a55b-4611-ace3-3592e7513a36
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 4668a8b6-2202-4788-aad8-07386c1bcc32
        userCondition: null
handle: default
hasTitleField: true
name: Standard
section: f09fdb2a-cbda-4d8b-a287-ecaf0d486d4a # External Links
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
