fieldLayouts:
  82b4b4a2-3c3d-4761-9174-86f04d612daf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 817b406c-4945-4784-9788-49231f7aa9b3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5727e741-e5ae-46f1-8446-12b507bac994 # Artikel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2ede62c-0737-4990-b067-064bd827765c
            userCondition: null
            warning: null
            width: 100
        name: Page
        uid: 801fbedc-fa76-4716-93b0-e86f9e452ac6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3e8cb3ca-dab5-441d-9dc5-a1d9a2fa4ca5 # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0098828-41cb-45f1-b9e3-e2c498443adb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f7028c3-83e0-4bd4-bedf-2d5066f0a521 # Artikeltyp
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30a7523b-8d10-42df-9fa4-b0e71a712aeb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f43ceeb-cd70-4a3f-a4d2-ef56820ae282 # Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18833d20-1179-49f3-aac4-e899c29bf7a8
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: 38e0bda3-7720-4b8a-ad63-a2a775de4d1c
        userCondition: null
handle: default
hasTitleField: true
name: Standard
section: 12e2b3a2-38d3-4aae-b6dd-92394501f149 # Newsfeed
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
