fieldLayouts:
  f4706b67-eb1c-43f9-8474-88d6baf1fdc6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a036edf5-d0e2-42e0-a065-14bd1746dd26
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6b958387-7d64-4b74-b25e-024b7acdb8e2 # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf03d21f-a650-49b3-8599-a445632cba49
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 66a0921c-ce39-4564-a7a7-312ff283966b # Titel der Website
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85c9d5fd-eade-43f8-9bd8-cc388a8dd8d2
            userCondition: null
            warning: null
            width: 100
        name: Titelbereich
        uid: 466fe377-645f-4c7d-b790-1b12e697e14a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c85719cd-5205-4bce-a16a-4ca8cb670c76 # Header Infobox
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a081ab43-de84-4ef5-94a2-a7b20aa1cf45
            userCondition: null
            warning: null
            width: 100
        name: Infobox
        uid: 884c7f02-ccfd-4c63-b6cb-4002833838bc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3dcb9279-424c-44e9-a64e-99741b4bca88 # Aktuelles
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2690c6d3-d1ff-46fb-9deb-5b611f9a2c60
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: acdd27ad-f040-43ed-be9c-cc3ca7449849 # Newseinträge
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b44b38ca-6884-48f0-b452-15de36f95c03
            userCondition: null
            warning: null
            width: 100
        name: Newsfeed
        uid: 2c796d17-9256-48f0-b58d-67e61271df56
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 8bcb303a-e7ae-4b94-be2f-e7a8a31f1541 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
