fieldLayouts:
  e5c642cb-8504-4045-a7cf-b0f370ba5734:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3777a085-06d2-424c-9e6f-e2a2c471d061 # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34eb7739-7597-44bc-b2ab-0447cbd27c4f
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 27a78151-c215-4888-ab96-60972c7805c0
            userCondition: null
            warning: null
            width: 100
        name: 'Darstellung auf Homepage'
        uid: 81c00f61-37d7-40b3-9621-c53018fa8d51
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 362fe411-bc28-4caf-9980-d3fc7fc955d0 # Page-Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eadbb9ef-6e48-49ae-b7a6-7342565242f8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6bb66f74-adc8-4919-9f78-89a964482176 # Ausführlicher Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a9ded5e-016b-408a-82c7-ae8dfe4e7718
            userCondition: null
            warning: null
            width: 100
        name: 'Darstellung der Unterseite'
        uid: b9545804-543c-435d-8890-df9e298b466a
        userCondition: null
handle: page
hasTitleField: true
name: Page
section: 13fa6ae6-827e-48e9-8873-1be1e1ad0dbf # Pages
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
