fieldLayouts:
  668aa223-04f0-4e86-83d6-82293e001bcc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3777a085-06d2-424c-9e6f-e2a2c471d061 # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10155ba6-781f-48f0-92a2-333883fa84f9
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d347100b-65dd-48d6-97ea-25342df1371c
            userCondition: null
            warning: null
            width: 100
        name: 'Darstellung auf Hompage'
        uid: f5d7d67c-14ca-4519-a87c-08715a1ed982
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 362fe411-bc28-4caf-9980-d3fc7fc955d0 # Page-Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79b189bd-f1cd-4d60-b32c-b3b888c6671a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6bb66f74-adc8-4919-9f78-89a964482176 # Ausführlicher Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba7c8a67-dec9-4be8-9eab-dc29392baf2b
            userCondition: null
            warning: null
            width: 100
        name: 'Darstellung der Unterseite'
        uid: 30134c8b-d27f-41cf-9a56-f70ef20679a4
        userCondition: null
handle: page
hasTitleField: true
name: Page
section: c7d84c5a-8797-4c50-a856-17a313e86dd8 # Pages
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
