fieldLayouts:
  f9acce4f-6bbf-4c14-82a9-5da0a7921f99:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bc12a536-6c41-475d-bcb3-038ba9e2a6bd
            warning: null
            width: 100
          -
            fieldUid: 360f35ce-147c-4f20-bc75-e17795ec57d0 # Fotos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7fe8f34-f3b3-4928-8aba-c54b021993b5
            warning: null
            width: 100
          -
            fieldUid: 6bb66f74-adc8-4919-9f78-89a964482176 # Ausführlicher Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67767cec-f59c-4eba-9fc5-79d61be3c9df
            warning: null
            width: 100
          -
            fieldUid: 2e9b7b8a-13ba-44f1-86df-f19e414e2f7f # Kurzbeschreibung
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 901a9911-6de2-4bb0-a2d1-7e63f6958a86
            warning: null
            width: 100
        name: Inhalt
        uid: 8d90499d-a2db-4f60-9f82-d8bbbd19a165
handle: vergangeneVeranstaltung
hasTitleField: true
name: 'Vergangene Veranstaltung'
section: b6aa21ff-b764-4f40-b410-3b12ca90a222 # Vergangene Veranstaltungen
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
