columnSuffix: mxitfjgm
contentColumnType: string(7)
fieldGroup: 59e772b9-cba7-4595-bc1b-d793dd49429a # Globals
handle: akzentfarbe2
instructions: 'Hier können Sie eine zweite Akzentfarbe für Buttons (Links zu internen/externen Seiten) einstellen.'
name: 'Akzentfarbe 2'
searchable: false
settings:
  defaultColor: '#d4d4d4'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
