columnSuffix: vefhmaqt
contentColumnType: string(7)
fieldGroup: 59e772b9-cba7-4595-bc1b-d793dd49429a # Globals
handle: akzentfarbe1
instructions: "Hier können Sie eine Akzentfarbe entsprechend Ihrer Corporate Identity auswählen. Diese wird in der Artikelüberschrift verwendet.\r\nFalls Sie hier nichts auswählen, haben diese Komponenten die gleiche schwarze Farbe wie der restliche Text."
name: 'Akzentfarbe 1'
searchable: false
settings:
  defaultColor: '#000000'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
