columnSuffix: vefhmaqt
contentColumnType: string(7)
fieldGroup: 59e772b9-cba7-4595-bc1b-d793dd49429a # Globals
handle: akzentfarbe1
instructions: 'Hier können Sie eine beliebige Akzentfarbe entsprechend auswählen, in welcher Teile des Textes (Datum, ''nächste Seite'' etc.) angezeigt werden.'
name: 'Akzentfarbe 1'
searchable: false
settings:
  defaultColor: '#000000'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
