columnSuffix: null
contentColumnType: string
fieldGroup: 7c955644-e560-4ceb-a37c-d63a20fb38a8 # Newsfeed
handle: artikelNewsfeed
instructions: null
name: Artikel
searchable: false
settings:
  contentTable: '{{%matrixcontent_artikelnewsfeed}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
