columnSuffix: sukjlhox
contentColumnType: text
fieldGroup: 280065d5-8d61-4f36-a5f6-7c4e119b3dfb # Homepage
handle: benennungNewsfeed
instructions: null
name: 'Benennung Newsfeed'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
