columnSuffix: xpmcgicd
contentColumnType: datetime
fieldGroup: 7c955644-e560-4ceb-a37c-d63a20fb38a8 # Newsfeed
handle: dateNewsfeed
instructions: null
name: Datum
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 5
  showDate: true
  showTime: true
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
