columnSuffix: bfctuxds
contentColumnType: datetime
fieldGroup: cbdc3555-7825-4900-b52d-36dc3dec2cfa # News
handle: datum
instructions: null
name: Datum
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
