columnSuffix: djrucjpt
contentColumnType: string(640)
fieldGroup: 24e64989-e24f-4bbc-8286-3a8f0d2f940a # SEO
handle: descriptionEntry
instructions: "Eine kurze Beschreibung des Artikels für SEO.\r\nDiese wird zB unter der Überschrift bei einer Google-Suche angezeigt. Bitte verwenden Sie höchstens 160 Zeichen."
name: 'Beschreibung '
searchable: false
settings:
  byteLimit: null
  charLimit: 160
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
