columnSuffix: null
contentColumnType: string
fieldGroup: 23279851-89cc-48c5-8a67-aa8bf053f893 # Externe Links
handle: externeLinks
instructions: null
name: 'Externe Links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_externelinks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
