columnSuffix: null
contentColumnType: string
fieldGroup: 59e772b9-cba7-4595-bc1b-d793dd49429a # Globals
handle: faviconFile
instructions: "Hier können Sie ein Bild hochladen, welches (z.B. im Browsertab) als Favicon angezeigt wird.\r\nDas beste Ergebnis wird mit einem quadratischen Bild erzielt. Im Falle eines nicht-quadratischen Bildes wird um das Zentrum des Bildes herum zurechtgeschnitten."
name: Favicon-Datei
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:92e31a9d-1a1a-4905-a8d0-fc18a00d2b9a' # Uploads
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:92e31a9d-1a1a-4905-a8d0-fc18a00d2b9a' # Uploads
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
