columnSuffix: zpqovmob
contentColumnType: text
fieldGroup: 24e64989-e24f-4bbc-8286-3a8f0d2f940a # SEO
handle: HTMLtitle
instructions: 'Der Titel der Website, wird bei der Suche und im Browsertab angezeigt.'
name: 'HTML Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
