columnSuffix: uhsfwuxk
contentColumnType: text
fieldGroup: 280065d5-8d61-4f36-a5f6-7c4e119b3dfb # Homepage
handle: infoboxTabelle
instructions: 'Hier können wichtige Informationen eingetragen werden, die sofort sichtbar sein sollen.'
name: 'Infobox Tabelle'
searchable: false
settings:
  addRowLabel: 'Zeile hinzufügen'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Info 1'
            -
              - handle
              - info1
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Info 2 '
            -
              - handle
              - info2
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - 'Info 3'
            -
              - handle
              - info3
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
        -
          - col3
          - ''
  maxRows: null
  minRows: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
