columnSuffix: null
contentColumnType: string
fieldGroup: 59e772b9-cba7-4595-bc1b-d793dd49429a # Globals
handle: infoboxInhalt
instructions: 'Hier können Sie einstellen, was in der Infobox angezeigt wird.'
name: 'Inhalt Infobox'
searchable: false
settings:
  contentTable: '{{%matrixcontent_infoboxinhalt}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
