columnSuffix: null
contentColumnType: string
fieldGroup: cbdc3555-7825-4900-b52d-36dc3dec2cfa # News
handle: newseintraege
instructions: null
name: Newseinträge
searchable: false
settings:
  contentTable: '{{%matrixcontent_newseintraege}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
