columnSuffix: hspseqha
contentColumnType: text
fieldGroup: 1057c348-12f1-4a0d-b548-7f404b04b6e5 # Pages
handle: pageTitel
instructions: null
name: Page-Titel
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
