columnSuffix: xmljfqtn
contentColumnType: text
fieldGroup: 59e772b9-cba7-4595-bc1b-d793dd49429a # Globals
handle: titelGlobals
instructions: null
name: Titel
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
