columnSuffix: rzpqatac
contentColumnType: text
fieldGroup: 59e772b9-cba7-4595-bc1b-d793dd49429a # Globals
handle: titelNewsfeed
instructions: 'Hier können Sie eine Überschrift für den Newsfeed eingeben.'
name: 'Titel Newsfeed'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: Newsfeed
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
