fieldLayouts:
  06da34d7-9b6c-4ccc-b856-345dc6a6efe7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e261e30b-0acf-433c-b2c1-7ee96b4c98e2 # Soll dieses Element angezeigt werden?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25e2f492-5b0f-4fc1-803b-4e04afe5696b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 46e4a549-c452-4c86-a78f-65d94063337f # Hintergrundfarbe Element
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a16c39f1-2198-4be2-9b34-d398e181c3e4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 508d09ee-ce8f-4b5b-8492-e73c99311ffb # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f2a1edc-4882-4c54-bd0b-5c054b0d7345
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6bb66f74-adc8-4919-9f78-89a964482176 # Ausführlicher Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41fc376d-8fac-459f-8530-996ff3902147
            userCondition: null
            warning: null
            width: 100
        name: Alert
        uid: 0c8b4d0d-d02d-43b9-9b52-f9552ceb87d4
        userCondition: null
handle: alert
name: Alert
sortOrder: 5
