fieldLayouts:
  9bbf98f0-2fe5-4a2f-b20a-d935e3126ea2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 131e509c-0eec-41c9-9506-d7f5886dac65 # Hintergrundfarbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fc5f5f2-81cb-4af0-9168-391b13869c73
            userCondition: null
            warning: null
            width: 100
        name: Farben
        uid: 19790f08-a625-4b2e-b3fc-269a31831251
        userCondition: null
handle: configuration
name: Allgemein
sortOrder: 1
