fieldLayouts:
  9bbf98f0-2fe5-4a2f-b20a-d935e3126ea2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 131e509c-0eec-41c9-9506-d7f5886dac65 # Hintergrundfarbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fc5f5f2-81cb-4af0-9168-391b13869c73
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bbef6044-7d82-45ad-9962-f61fe5f6c388 # Akzentfarbe 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa22b1d5-57f6-49b9-8d89-007eba49bb40
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 63e479fb-c527-440e-ba46-417bbb5fe5eb # Akzentfarbe 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d668cc1-459d-43b6-90a9-9639c41ecc2e
            userCondition: null
            warning: null
            width: 100
        name: Farben
        uid: 19790f08-a625-4b2e-b3fc-269a31831251
        userCondition: null
handle: configuration
name: Allgemein
sortOrder: 1
