fieldLayouts:
  1040b0df-e749-40fa-bdc1-ddabc9559bdf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e261e30b-0acf-433c-b2c1-7ee96b4c98e2 # Aktiviert
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15ead782-28f2-4e21-b072-e196b649d61a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 508d09ee-ce8f-4b5b-8492-e73c99311ffb # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 398204eb-1662-423c-9ad7-f330026e4733
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6bb66f74-adc8-4919-9f78-89a964482176 # Ausführlicher Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 033322a0-c3ec-4ac6-81a1-7e2d4f668edb
            userCondition: null
            warning: null
            width: 100
        name: Faktenbox
        uid: 98eacfc8-0111-4406-8370-04e2c683d2a1
        userCondition: null
handle: faktenboxA
name: 'Faktenbox A'
sortOrder: 5
