fieldLayouts:
  a8b894ed-3bad-44e6-9e2e-ae32255bd17d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0fc3c784-7fa8-4f25-8ef3-0ce90302f053 # Favicon-Datei
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8cf3e11-bfb6-4ab4-8c5c-79e77ccc11e0
            userCondition: null
            warning: null
            width: 100
        name: Favicon
        uid: 20f05aaf-5ddd-48be-b3a7-07a5dbc39735
        userCondition: null
handle: favicon
name: Favicon
sortOrder: 1
