fieldLayouts:
  ed448786-57af-4b9d-a850-7c1c5ac57de7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e261e30b-0acf-433c-b2c1-7ee96b4c98e2 # Soll dieses Element angezeigt werden?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 138e9e38-bb91-40ee-87d1-39632e90823b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b93ffd04-3321-4db7-8daa-76bff95506e1 # Titel Newsfeed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6863aa8-a04a-49bf-afa0-bbe1214f5469
            userCondition: null
            warning: null
            width: 100
        name: Titel
        uid: 61631b80-fe4f-48b6-b184-853ae1ed6db6
        userCondition: null
handle: newsfeedTitel
name: 'Newsfeed Titel'
sortOrder: 4
