fieldLayouts:
  4d7f33a5-a0d5-4bf5-bc93-7fca53db3363:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e261e30b-0acf-433c-b2c1-7ee96b4c98e2 # Aktiviert
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a188f65a-a3fe-414d-b663-079e9cdc0d4d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f1e2a9cf-f5eb-40d4-81f8-90cf1653a033 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad8ecbe4-2cb6-4be8-9fc7-b2d2e12a762b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 508d09ee-ce8f-4b5b-8492-e73c99311ffb # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 923582e3-a81a-4471-8d2a-da65001dbd52
            userCondition: null
            warning: null
            width: 100
        name: 'Teaser A'
        uid: 5f0709dd-ee88-4cbd-b3dd-31629a929b3d
        userCondition: null
handle: teaserA
name: 'Teaser A'
sortOrder: 3
