defaultPlacement: end
enableVersioning: true
handle: externalLinks
name: 'External Links'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  36abde1f-5a22-485e-8435-a4fb6ac82354: # knappe1a
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 9d1232c8-e7b4-4ac7-a5ef-ed2aa6736612
type: structure
